busstops/urls.py
from django.urls import path
from . import views

app_name = 'busstops'

urlpatterns = [
    path('', views.index_view, name='index'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

registration/urls.py
from django.urls import path
from . import views

app_name = 'registration'

urlpatterns = [
    path('', views.index_view, name='index'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
]

busstops/models.py
from django.db import models

# Create your models here.

busstops/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from utils import scraper
import json


@login_required
def index_view(request):
    if request.method == 'POST':
        data = request.body
        results = scraper.run(data)
        print(results)
        return HttpResponse(results)
    else:
        return render(request, 'busstops/bus-search.html')

busstops/templates/busstops/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <link rel="stylesheet" href="{% static 'busstops/css/bus-search.css' %}">
  <title>Document</title>
</head>
<body>
  {% block content %}
  {% endblock %}
</body>
</html>

busstops/templates/busstops/bus-search.html
{% extends "busstops/base.html" %}
{% load static %}

{% block content %}
{% csrf_token %}

<nav class="page-nav">
  <a class="logout-link" href="{% url 'registration:logout' %}">Wyloguj się</a>
</nav>

<header class="page-header">
  <h1>Wyszukiwarka połączeń</h1>
</header>

<div role="search" class="search-area">
  <div class="form-group">
    <label for="from">Z:</label>
    <input class="text-input" type="search" id="from">
  </div>

  <button id="reverse" class="reverse-button">&#8646;</button>
  <div class="form-group">
    <label for="to">Do:</label>
    <input class="text-input" type="search" id="to">
  </div>
  <button class="submit-button" id="search">Wyszukaj</button>
</div>

<div id="tableData" class="data-table">

</div>

<script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>
<script src="{% static 'busstops/js/main.js' %}"></script>
{% endblock %}